### ISSUE TITLE
Go module paths tracking issue

### ISSUE THREAD

**Issue by ydnar** [bytecodealliance/wasm-tools-go#232]
- [x] POC [go.bytecodealliance.org](https://go.bytecodealliance.org) with duplicate repo at https://github.com/bytecodealliance/go-modules
- [ ] Set up CNAME for go.bytecodealliance.org → bytecodealliance.github.io (@ricochet)
- [ ] Delete POC https://github.com/bytecodealliance/go-modules repo
- [ ] Rename https://github.com/bytecodealliance/wasm-tools-go → https://github.com/bytecodealliance/go-modules
- [ ] Fork https://github.com/bytecodealliance/go-modules → https://github.com/bytecodealliance/wasm-tools-go
- [ ] Mass find & replace `github.com/bytecodealliance/wasm-tools-go` → `go.bytecodealliance.org` in https://github.com/bytecodealliance/go-modules repo
- [ ] Enable GitHub pages on https://github.com/bytecodealliance/go-modules repo @ `go.bytecodealliance.org`
- [ ] [Deprecate the github.com/bytecodealliance/wasm-tools-go module](https://go.dev/ref/mod#go-mod-file-module-deprecation)

**Comment by lxfontes** [comment]
we also talked about a blog post, but didn't get into details on where/when/content

**Comment by Mossaka** [comment]
I am happy to draft a blog post based on the talk @ydnar and I will present at WasmCon

**Comment by ydnar** [comment]
Looks like @Mossaka has the blog post. I’ll keep this tracking issue open until we post it!
